version: '3'
services:
  pg:
    image: postgres:10.4
    ports:
      - "5432:5432"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/rails_app_for_tech_train
      - bundle:/bundle
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - '3000:3000'
    depends_on:
      - pg
    tty: true
    stdin_open: true
volumes:
  bundle:
    driver: local
